//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPL.FitOS.LibraryAPI.ResponseMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages 
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTPL.FitOS.LibraryAPI.ResponseMessages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey ! Wrong Inputs,Looking for Column Names - Classification &amp; KeyedName..
        /// </summary>
        public static string CheckInputsForPlColours {
            get {
                return ResourceManager.GetString("CheckInputsForPlColours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey ! Wrong Inputs,Looking for Column Names - Classification &amp; PlEmailId..
        /// </summary>
        public static string CheckInputsForPlSupp_factory {
            get {
                return ResourceManager.GetString("CheckInputsForPlSupp&factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Records are found..
        /// </summary>
        public static string DataFound {
            get {
                return ResourceManager.GetString("DataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey ! Wrong Inputs,Looking for Column Names - CreatedById Or ModifiedById Or Both..
        /// </summary>
        public static string GetUserName {
            get {
                return ResourceManager.GetString("GetUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Inserted Or Updated successfully..
        /// </summary>
        public static string InsertedRecord {
            get {
                return ResourceManager.GetString("InsertedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey ! No matching record found, Please refine your search creteria..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted successfully..
        /// </summary>
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide mandatory fields like CreatedOn,ModifiedOn,Id,IsDeleted,KeyedName etc.. .
        /// </summary>
        public static string ValidateData {
            get {
                return ResourceManager.GetString("ValidateData", resourceCulture);
            }
        }
    }
}
